version: '3.8'

services:

  substation1:
    build:
      context: ./substation_service
    container_name: substation1
    ports:
      - "8001:8000"
      - "9101:9100"

  substation2:
    build:
      context: ./substation_service
    container_name: substation2
    ports:
      - "8002:8000"
      - "9102:9100"

  substation3:
    build:
      context: ./substation_service
    container_name: substation3
    ports:
      - "8003:8000"
      - "9103:9100"

  load_balancer:
    build:
      context: ./load_balancer
    container_name: load_balancer
    depends_on:
      - substation1
      - substation2
      - substation3

  charge_request:
    build:
      context: ./charge_request_service
    container_name: charge_request
    ports:
      - "8080:5000"
    depends_on:
      - load_balancer

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
